{
    "openapi": "3.0.1",
    "info": {
      "title": "API o Aplicativo de Registro de Memorias",
      "description": "Essa API tem o objetivo de implementar os casos de uso, estrutura de segurança e outros elementos atinentes ao backend para a aplicação",
      "contact": {
        "name": "Suporte",
        "email": "leonardocostapsi@gmail.com"
      },
      "version": "1.0.0"
    },
    "paths": {
      "/session": {
        "post": {
          "description": "Autentica o usuário na aplicação!",
          "tags": [
            "Usuários"
          ],
          "requestBody": {
            "description": "O usuário é autenticado na aplicação informando as suas credenciais de acesso.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserLoginRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Login realizado com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/UserLoginResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Email ou senha incorreta."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/me": {
        "get": {
          "description": "Retorna os dados do usuário logado",
          "tags": [
            "Usuários"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "responses": {
            "200": {
              "description": "Successo.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/GetCurrentUserResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Token inválido."
            },
            "404": {
              "description": "Usuário não encontrado."
            },
            "500": {
              "description": "Erro servidor."
            }
          }
        }
      },
      "/users": {
        "get": {
          "description": "Retorna todos usuários",
          "tags": [
            "Usuários"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "responses": {
            "200": {
              "description": "Usuários retornados sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RegisterUserResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Usuário já foi cadastrado."
            },
            "500": {
              "description": "Erro servidor."
            }
          }
        },
        "post": {
          "description": "Registro de um usuário",
          "tags": [
            "Usuários"
          ],
          "requestBody": {
            "description": "Dados necessários para cadastro de um usuário",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterUserRequest"
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Usuário criado com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RegisterUserResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Usuário já foi cadastrado."
            },
            "500": {
              "description": "Erro servidor."
            }
          }
        }
      },
      "/avatar/{userId}": {
        "put": {
          "description": "Atualiza o avatar do usuário.",
          "tags": [
            "Usuários"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"userId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "requestBody": {
            "description": "Dados necessários para alteração do avatar de um usuário",
            "content": {
              "multipart/form-data": {
                "schema": {
                  "$ref": "#/components/schemas/UserAvatarUpdateRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Login realizado com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/UserAvatarUpdateResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Imagem não enviada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/allmemories": {
        "get": {
          "description": "Retorna todas as memórias dos usuários ordenadas por sua publicação.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "responses": {
            "200": {
              "description": "Memorias retornadas com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/GetAllMemoriesFromApp"
                  }
                }
              }
            },
            "401": {
              "description": "Token inválido ou expirado."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/memories": {
        "get": {
          "description": "Retorna todas as memórias do usuário autenticado.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "responses": {
            "200": {
              "description": "Memorias retornadas com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/GetMemoriesCurrentUser"
                  }
                }
              }
            },
            "401": {
              "description": "Token inválido ou expirado."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        },
        "post": {
          "description": "Criação de memória do usuário.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "requestBody": {
            "description": "Dados necessários para cadastro de uma memória",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateMemoryRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Memoria criada com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/CreateMemoryResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Token inválido ou expirado."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/memories/{memoryId}": {
        "put": {
          "description": "Atualizar uma memória.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"memoryId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "requestBody": {
            "description": "Dados necessários para atualizar a memória",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateMemoryRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Memória atualizada com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/UpdateMemoryResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Memória não localizada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        },
        "delete": {
          "description": "Deleta uma memória.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"memoryId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Memória deletada com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/DeleteMemoryMediaResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Imagem não localizada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/medias": {
        "post": {
          "description": "O usuário adiciona medias à sua lembrança ex: fotos e videos.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "requestBody": {
            "description": "O usuário adiciona midias em sua memória.",
            "content": {
              "multipart/form-data": {
                "schema": {
                  "$ref": "#/components/schemas/CreateMemoryMediaRequest"
                }
                
              }
            }
          },
          "responses": {
            "200": {
              "description": "Medias subidas resposta.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/CreateMemoryMediaResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Ocorreu algum erro."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/medias/{mediaId}": {
        "delete": {
          "description": "Deleta mídia de uma memória.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"mediaId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Mídia deletada com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/DeleteMemoryMediaResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Imagem não localizada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/usersinmemory": {
        "post": {
          "description": "Adiciona usuários à memória.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "requestBody": {
            "description": "Adiciona usuários á memória.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddPeopleInMemoryRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Usuários adicionados com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/AddPeopleInMemoryResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Imagem não localizada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/usersinmemory/{memoryId}/{userId}": {
        "delete": {
          "description": "Remove um usuário da memória",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"memoryId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            },
            {
              "in":"path",
              "name":"userId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Usuário removido da memória com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/RemovePeoplesInMemoryResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Usuário ou memória não localizada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/reflections": {
        "post": {
          "description": "O usuário adiciona uma reflexão à sua lembrança.",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "requestBody": {
            "description": "O usuário cria uma reflexão em sua lembrança.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateReflectionRequest"
                }
                
              }
            }
          },
          "responses": {
            "200": {
              "description": "Reflexão criada com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/CreateReflectionResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Ocorreu algum erro."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/reflections/{reflectionId}": {
        "put": {
          "description": "Atualiza uma reflexão da memória",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"reflectionId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "requestBody": {
            "description": "Dados necessários para atualizar a reflexão da memória",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateReflectionRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Reflexão da memória alterada com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/DeleteReflectionResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Usuário ou memória não localizada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        },
        "delete": {
          "description": "Remove uma reflexão da memória",
          "tags": [
            "Memorias"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"reflectionId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Reflexão removida da memória com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/DeleteReflectionResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Usuário ou memória não localizada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/stickynotes": {
        "get": {
          "description": "Retorna todas os lembretes do usuário autenticado.",
          "tags": [
            "Sticky Notes"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "responses": {
            "200": {
              "description": "Lembretes retornados com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/GetStickyNotesCurrentUserResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Token inválido ou expirado."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        },
        "post": {
          "description": "Criação de lembrete do usuário.",
          "tags": [
            "Sticky Notes"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "requestBody": {
            "description": "Dados necessários para cadastro de uma memória",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateStickyNotesRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Lembrete criado com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/CreateStickyNotesResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Token inválido ou expirado."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      },
      "/stickynotes/{stickyNotesId}": {
        "put": {
          "description": "Atualiza um Sticky Notes",
          "tags": [
            "Sticky Notes"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"stickyNotesId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "requestBody": {
            "description": "Dados necessários para atualizar Sticky Notes",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateStickyNotesRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Sticky Notes atualizado com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/UpdateStickyNotesResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Usuário ou memória não localizada."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        },
        "delete": {
          "description": "Deleta um lembrete da memória",
          "tags": [
            "Sticky Notes"
          ],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters":[
            {
              "in":"path",
              "name":"stickyNotesId",
              "schema":{
                "items": {
                  "type":"string"
                }
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Lembrete deletado com sucesso.",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/DeleteStickyNotesResponse"
                  }
                }
              }
            },
            "400": {
              "description": "Lembrete não localizado."
            },
            "500": {
              "description": "Erro no servidor."
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "RegisterUserRequest": {
          "type": "object",
          "properties": {
            "email": {
              "description": "E-mail do usuário que será criado.",
              "type": "string",
              "example": "enzopinheiro6@gmail.com"
            },
            "name": {
              "description": "Nome completo do usuário que será criado.",
              "type": "string",
              "example": "Enzo Gabriel Pinheiro de Leão"
            },
            "username": {
              "description": "Nome de usuário que será identificado no @.",
              "type": "string",
              "example": "enzoleao22"
            },
            "number": {
              "description": "Número do usuário.",
              "type": "string",
              "example": "91991611201"
            },
            "birthday": {
              "description": "Senha do usuario que vai se cadastrar.",
              "type": "string",
              "example": "2011-10-05T14:48:00.000Z"
            },
            "password": {
              "description": "Senha do usuario que vai se cadastrar.",
              "type": "string",
              "example": "default32312"
            }
          },
          "required": [
            "email",
            "name",
            "password"
          ]
        },
        "RegisterUserResponse": {
          "type": "object",
          "properties": {
            "id": {
              "description": "Identificador do usuário criado.",
              "type": "string",
              "format": "uuid",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "name": {
              "description": "Nome completo do usuário criado.",
              "type": "string",
              "example": "Enzo Gabriel Pinheiro de Leão"
            },
            "email": {
              "description": "Email do usuario criado.",
              "type": "string",
              "example": "enzopinheiro6@gmail.com"
            },
            "avatar": {
              "description": "Avatar do usuario.",
              "type": "string",
              "example": null
            },
            "username": {
              "description": "Nome de usuário @.",
              "type": "string",
              "example": "enzoleao22"
            },
            "number": {
              "description": "Numero do usuário.",
              "type": "string",
              "example": "9199161210"
            },
            "birthday": {
              "description": "Avatar do usuario.",
              "type": "datetime",
              "example": "2011-10-05T14:48:00.000Z"
            }
          }
        },
        "UserLoginRequest": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "Email do usuário.",
              "example": "enzopinheiro6@gmail.com"
            },
            "password": {
              "type": "string",
              "description": "A senha do usuário.",
              "exameple":"default123"
            }
          },
          "required": [
            "email",
            "password"
          ]
        },
        "UserLoginResponse": {
          "type": "object",
          "properties": {
            "user": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Identificador do usuário",
                  "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
                },
                "name": {
                  "type": "string",
                  "description": "Nome do usuário logado",
                  "example": "Enzo Gabriel Pinheiro de Leão"
                },
                "email": {
                  "type": "string",
                  "description": "Email do usuário logado",
                  "example": "enzopinheiro6@gmail.com"
                },
                "avatar": {
                  "type": "string",
                  "description": "Avatar do usuário",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                },
                "birthday": {
                  "type": "string",
                  "description": "Data de nascimento do usuário",
                  "example": "2011-10-05T14:48:00.000Z"
                }
              }
            },
            "token": {
              "type": "string",
              "description": "Token concedido ao usuário logado",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzY3Mjc4MzQsImV4cCI6MTY3NjgxNDIzNCwic3ViIjoiOSJ9.dhue4XHYW4mNBGqKfrp6QG15xO3QcieGvzSAjbXdizw"
            }
          }
        },
        "GetAllUsersResponse": {
          "type": "object",
          "properties": {
            "user": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Identificador do usuário",
                  "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
                },
                "name": {
                  "type": "string",
                  "description": "Nome do usuário logado",
                  "example": "Enzo Gabriel Pinheiro de Leão"
                },
                "email": {
                  "type": "string",
                  "description": "Email do usuário logado",
                  "example": "enzopinheiro6@gmail.com"
                },
                "avatar": {
                  "type": "string",
                  "description": "Avatar do usuário",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                },
                "birthday": {
                  "type": "string",
                  "description": "Data de nascimento do usuário",
                  "example": "2011-10-05T14:48:00.000Z"
                }
              }
            },
            "token": {
              "type": "string",
              "description": "Token concedido ao usuário logado",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzY3Mjc4MzQsImV4cCI6MTY3NjgxNDIzNCwic3ViIjoiOSJ9.dhue4XHYW4mNBGqKfrp6QG15xO3QcieGvzSAjbXdizw"
            }
          }
        },
        "UserAvatarUpdateRequest": {
          "type": "object",
          "properties": {
            "avatar": {
              "type": "file",
              "description": "Imagem de avatar para ser enviada"
            }
          },
          "required": [
            "avatar"
          ]
        },
        "UserAvatarUpdateResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Identificador unico do usuário que teve o avatar alterado",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "avatar": {
              "type": "string",
              "description": "Avatar atualizado",
              "example": "http://localhost:3001/public/1683332087058.jpeg"
            }
          }
        },
        "GetCurrentUserResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Identificador do usuário.",
              "format": "string",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "avatar": {
              "type": "string",
              "description": "Avatar do usuário.",
              "format": "string",
              "example": "http://localhost:3000/public/1683070164692.jpeg"
            },
            "name": {
              "type": "string",
              "description": "Nome do usuário",
              "format": "string",
              "example": "Enzo Gabriel Pinheiro de Leao"
            },
            "email": {
              "type": "string",
              "description": "Email do usuário",
              "format": "string",
              "example": "enzopinheiro6@gmail.com"
            }
            ,
            "birthday": {
              "type": "string",
              "description": "Email do usuário",
              "format": "string",
              "example": "2011-10-05T14:48:00.000Z"
            }
          }
        },
        "GetMemoriesCurrentUser": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number",
              "description":"Identificador unico da memória",
              "format":"number",
              "example":"eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "name": {
              "type": "string",
              "description":"Nome da lembrança",
              "format":"string",
              "example":"Lembranças de verão"
            },
            "usersInMemory": {
              "type": "array",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Identificador do usuário",
                  "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
                },
                "name": {
                  "type": "string",
                  "description": "Nome do usuário logado",
                  "example": "Enzo Gabriel Pinheiro de Leão"
                },
                "email": {
                  "type": "string",
                  "description": "Email do usuário logado",
                  "example": "enzopinheiro6@gmail.com"
                },
                "avatar": {
                  "type": "string",
                  "description": "Avatar do usuário",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                }
              },
              "example":[
                {
                  "id":"eb51ab14-8e56-4170-87c8-436fca6a8312",
                  "name":"Enzo",
                  "avatar":"http://localhost:3001/public/1683318820660.jpeg",
                  "email":"enzopinheiro6@gmail.com"
                }
              ]
            },
            "reflections": {
              "type": "array",
              "items": {
                "id": {
                  "type": "number",
                  "description": "Identificador do usuário",
                  "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
                },
                "name": {
                  "type": "string",
                  "description": "Nome do usuário logado",
                  "example": "Enzo Gabriel Pinheiro de Leão"
                },
                "email": {
                  "type": "string",
                  "description": "Email do usuário logado",
                  "example": "enzopinheiro6@gmail.com"
                },
                "avatar": {
                  "type": "string",
                  "description": "Avatar do usuário",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                }
              },
              "example":[
                {
                  "id":"eb51ab14-8e56-4170-87c8-436fca6a8312",
                  "content":"Boas lembranças"
                }
              ]
            },
            "media": {
              "type": "array",
              "properties": {
                "id": {
                  "type": "number",
                  "description": "Identificador unico da midia da memoria",
                  "example": 1
                },
                "src": {
                  "type": "string",
                  "description": "Link para acessar a memória",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                }
              },
              "example":[
                {
                  "id":"eb51ab14-8e56-4170-87c8-436fca6a8312", 
                  "src":"http://localhost:3001/public/1683317414920.jpeg"
                }
              ]
            },
            "location": {
              "type": "array",
              "properties": {
                "id": {
                  "type": "number",
                  "description": "Identificador do usuário",
                  "example": 1
                }
              },
              "example":[]
            },
            "createdAt": {
              "type": "string",
              "description": "Data no qual a memória foi criada",
              "example": "2023-05-05T20:07:31.309Z"
            }
          }
        },
        "GetAllMemoriesFromApp": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number",
              "description":"Identificador unico da memória",
              "format":"number",
              "example":"eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "name": {
              "type": "string",
              "description":"Nome da lembrança",
              "format":"string",
              "example":"Lembranças de verão"
            },
            "author": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Identificador do usuário",
                  "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
                },
                "name": {
                  "type": "string",
                  "description": "Nome do usuário logado",
                  "example": "Enzo Gabriel Pinheiro de Leão"
                },
                "email": {
                  "type": "string",
                  "description": "Email do usuário logado",
                  "example": "enzopinheiro6@gmail.com"
                },
                "avatar": {
                  "type": "string",
                  "description": "Avatar do usuário",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                }
              },
              "example": {
                  "id":"eb51ab14-8e56-4170-87c8-436fca6a8312",
                  "name":"Enzo",
                  "avatar":"http://localhost:3001/public/1683318820660.jpeg",
                  "email":"enzopinheiro6@gmail.com"
                }
              
            },
            "usersInMemory": {
              "type": "array",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Identificador do usuário",
                  "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
                },
                "name": {
                  "type": "string",
                  "description": "Nome do usuário logado",
                  "example": "Enzo Gabriel Pinheiro de Leão"
                },
                "email": {
                  "type": "string",
                  "description": "Email do usuário logado",
                  "example": "enzopinheiro6@gmail.com"
                },
                "avatar": {
                  "type": "string",
                  "description": "Avatar do usuário",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                }
              },
              "example":[
                {
                  "id":"eb51ab14-8e56-4170-87c8-436fca6a8312",
                  "name":"Enzo",
                  "avatar":"http://localhost:3001/public/1683318820660.jpeg",
                  "email":"enzopinheiro6@gmail.com"
                }
              ]
            },
            "reflections": {
              "type": "array",
              "items": {
                "id": {
                  "type": "number",
                  "description": "Identificador do usuário",
                  "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
                },
                "name": {
                  "type": "string",
                  "description": "Nome do usuário logado",
                  "example": "Enzo Gabriel Pinheiro de Leão"
                },
                "email": {
                  "type": "string",
                  "description": "Email do usuário logado",
                  "example": "enzopinheiro6@gmail.com"
                },
                "avatar": {
                  "type": "string",
                  "description": "Avatar do usuário",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                }
              },
              "example":[
                {
                  "id":"eb51ab14-8e56-4170-87c8-436fca6a8312",
                  "content":"Boas lembranças"
                }
              ]
            },
            "media": {
              "type": "array",
              "properties": {
                "id": {
                  "type": "number",
                  "description": "Identificador unico da midia da memoria",
                  "example": 1
                },
                "src": {
                  "type": "string",
                  "description": "Link para acessar a memória",
                  "example": "http://localhost:3000/public/1683069498402.jpeg"
                }
              },
              "example":[
                {
                  "id":"eb51ab14-8e56-4170-87c8-436fca6a8312", 
                  "src":"http://localhost:3001/public/1683317414920.jpeg"
                }
              ]
            },
            "location": {
              "type": "array",
              "properties": {
                "id": {
                  "type": "number",
                  "description": "Identificador do usuário",
                  "example": 1
                }
              },
              "example":[]
            },
            "createdAt": {
              "type": "string",
              "description": "Data no qual a memória foi criada",
              "example": "2023-05-05T20:07:31.309Z"
            }
          }
        },
        "CreateMemoryRequest": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Nome da memória",
              "format":"string",
              "example": "Lembranças de verão"
            },
            "usersInMemory": {
              "type":"array",
              "format":"array",
              "example":[
                "eb51ab14-8e56-4170-87c8-436fca6a8312",
                "eb51ab14-8e56-4170-87c8-436fca6a8312",
                "eb51ab14-8e56-4170-87c8-436fca6a8312"
              ],
              "description":"Array com os Identificadores únicos dos usuarios que estão presente na memória"
            }
          },
          "required": [
            "name"
          ]
        },
        "CreateMemoryResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number",
              "format":"number",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "name": {
              "type": "string",
              "format":"string",
              "example": "Lembranças de verão"
            },
            "authorId": {
              "type":"string",
              "format":"uuid",
              "example":"eb51ab14-8e56-4170-87c8-436fca6a8312"       
            },
            "createdAt": {
              "type":"datetime",
              "format":"datetime",
              "example":"2023-05-08T02:48:23.862Z"    
            }
          }
        },
        "UpdateMemoryRequest": {
          "type": "object",
          "properties": {
            "memoryName": {
              "type": "string",
              "description": "Nome da memória",
              "format":"string",
              "example": "Lembranças de verão"
            }
          },
          "required": [
            "name"
          ]
        },
        "UpdateMemoryResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number",
              "format":"number",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "name": {
              "type": "string",
              "format":"string",
              "example": "Lembranças de verão"
            },
            "authorId": {
              "type":"string",
              "format":"uuid",
              "example":"eb51ab14-8e56-4170-87c8-436fca6a8312"       
            },
            "createdAt": {
              "type":"datetime",
              "format":"datetime",
              "example":"2023-05-08T02:48:23.862Z"    
            }
          }
        },
        "AddPeopleInMemoryRequest": {
          "type": "object",
          "properties": {
            "memoryId": {
              "type": "string",
              "description": "Identificador unico da memória",
              "format":"string",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "usersInMemory": {
              "type":"array",
              "format":"array",
              "example":[
                "eb51ab14-8e56-4170-87c8-436fca6a8312",
                "eb51ab14-8e56-4170-87c8-436fca6a8312",
                "eb51ab14-8e56-4170-87c8-436fca6a8312"
              ],
              "description":"Array com os Identificadores únicos dos usuarios que serão adicionados na memória"
            }
          },
          "required": [
            "name"
          ]
        },
        "AddPeopleInMemoryResponse": {
          "type": "object",
          "properties": {
            "memoryId": {
              "type": "string",
              "description": "Identificador unico da memória",
              "format":"string",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "usersAddInMemory": {
              "type":"number",
              "format":"number",
              "example":1,
              "description":"Array com os Identificadores únicos dos usuarios que serão adicionados na memória"
            }
          },
          "required": [
            "name"
          ]
        },
        "RemovePeoplesInMemoryResponse": {
          "type": "object",
          "properties": {
            "userRemoved": {
              "type": "string",
              "description": "Identificador unico do usuário removido",
              "format":"string",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            }
          }
          
        },
        "CreateMemoryMediaRequest": {
          "type": "object",
          "properties": {
            "memoryId": {
              "type": "number",
              "description": "Identificador unico da memória",
              "example": "1"
            },
            "medias": {
              "type":"array",
              "items": {
                "type":"string",
                "format":"binary"
              }
            }
          }
        },
        "CreateMemoryMediaResponse": {
          "type": "object",
          "properties": {
            "imagesUploadeds": {
              "type": "number",
              "example": "3"
            },
            "message": {
              "type":"string",
              "example":"Imagens subidas com sucesso"       
            }
          }
        },
        "DeleteMemoryMediaResponse": {
          "type": "object",
          "properties": {
            "medias": {
              "type":"string",
              "example":"77b35965-95c2-4189-a39d-d56f3ada810d"       
            },
            "message": {
              "type":"string",
              "example":"Imagem deletada com sucesso"       
            }
          }
        },
        "CreateReflectionRequest": {
          "type": "object",
          "properties": {
            "memoryId": {
              "type":"string",
              "example":"77b35965-95c2-4189-a39d-d56f3ada810d"       
            },
            "content": {
              "type":"string",
              "example":"Estava muito divertido nesse dia"       
            }
          }
        },
        "CreateReflectionResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type":"string",
              "example":"77b35965-95c2-4189-a39d-d56f3ada810d"       
            },
            "content": {
              "type":"string",
              "example":"Este dia estava muito divertido"       
            },
            "authorId": {
              "type":"string",
              "example":"eb51ab14-8e56-4170-87c8-436fca6a8312"       
            },
            "createdAt": {
              "type":"datetime",
              "example":"2023-05-11T23:38:14.865Z"       
            }
          }
        },
        "UpdateReflectionRequest": {
          "type": "object",
          "properties": {

            "content": {
              "type":"string",
              "example":"Este dia estava muito divertido"       
            }
          }
        },
        "DeleteReflectionResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type":"string",
              "example":"77b35965-95c2-4189-a39d-d56f3ada810d"       
            },
            "content": {
              "type":"string",
              "example":"Este dia estava muito divertido"       
            },
            "memoryId": {
              "type":"string",
              "example":"77b35965-95c2-4189-a39d-d56f3ada810d"       
            },
            "createdAt": {
              "type":"datetime",
              "example":"2023-05-11T23:38:14.865Z"       
            }
          }
        },
        "GetStickyNotesCurrentUserResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Identificador do lembrete.",
              "format": "string",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "content": {
              "type": "string",
              "description": "Conteúdo do lembrete",
              "format": "string",
              "example": "Neste dia eu irei viajar ao Rio de Janeiro"
            },
            "authorId": {
              "type": "string",
              "description": " Identificador unicod do Autor do lembrete",
              "format": "string",
              "example": "b83dac1e-6c05-47de-be09-e9e26fd3cb8c"
            },
            "date": {
              "type": "string",
              "description": "Data que acontecerá o lembrete",
              "format": "string",
              "example": "2023-10-05T14:48:00.000Z"
            },
            "createdAt": {
              "type": "string",
              "description": "Data que o lembrete foi gerado",
              "format": "string",
              "example": "2023-10-05T14:48:00.000Z"
            }
          }
        },
        "CreateStickyNotesRequest": {
          "type": "object",
          "properties": {
            "content": {
              "type": "string",
              "description": "Conteudo do lembrete",
              "format":"string",
              "example": "Neste dia eu irei viajar ao Rio de Janeiro"
            },
            "date": {
              "type":"string",
              "format":"string",
              "example":"2023-05-08T02:48:23.862Z",
              "description":"Array com os Identificadores únicos dos usuarios que estão presente na memória"
            }
          },
          "required": [
            "name"
          ]
        },
        "CreateStickyNotesResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number",
              "format":"number",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "content": {
              "type": "string",
              "format":"string",
              "example": "Lembranças de verão"
            },
            "authorId": {
              "type":"string",
              "format":"uuid",
              "example":"eb51ab14-8e56-4170-87c8-436fca6a8312"       
            },
            "date": {
              "type":"datetime",
              "format":"datetime",
              "example":"2023-05-08T02:48:23.862Z"    
            },
            "createdAt": {
              "type":"datetime",
              "format":"datetime",
              "example":"2023-05-08T02:48:23.862Z"    
            }
          }
        },
        "DeleteStickyNotesResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number",
              "format":"number",
              "example": "eb51ab14-8e56-4170-87c8-436fca6a8312"
            },
            "content": {
              "type": "string",
              "format":"string",
              "example": "Lembranças de verão"
            },
            "authorId": {
              "type":"string",
              "format":"uuid",
              "example":"eb51ab14-8e56-4170-87c8-436fca6a8312"       
            },
            "date": {
              "type":"datetime",
              "format":"datetime",
              "example":"2023-05-08T02:48:23.862Z"    
            },
            "createdAt": {
              "type":"datetime",
              "format":"datetime",
              "example":"2023-05-08T02:48:23.862Z"    
            }
          }
        },
        "UpdateStickyNotesRequest": {
          "type": "object",
          "properties": {
            "content": {
              "type":"string",
              "example":"Neste dia terei uma reunião"       
            },
            "date": {
              "type":"datetime",
              "example":"2023-01-01T14:48:00.000Z"       
            }
          }
        },
        "UpdateStickyNotesResponse": {
          "type": "object",
          "properties": {
            "id": {
              "type":"string",
              "example":"77b35965-95c2-4189-a39d-d56f3ada810d"       
            },
            "content": {
              "type":"string",
              "example":"Este dia estava muito divertido"       
            },
            "memoryId": {
              "type":"string",
              "example":"77b35965-95c2-4189-a39d-d56f3ada810d"       
            },
            "createdAt": {
              "type":"datetime",
              "example":"2023-05-11T23:38:14.865Z"       
            }
          }
        }
      },
      "securitySchemes": {
        "bearerAuth": {
          "description": "Autenticação utilizando JWT",
          "type": "http",
          "scheme": "Bearer",
          "bearerFormat": "JWT"
        }
      }
    }
  }